### ISSUE TITLE
Intron mutants

### ISSUE THREAD

**Issue by khybiske** [SuLab/WikiGenomesBase#89]
A handful of intron mutants exist (<10) with PMID references. The field will be interested if chlambase could annotate them. For implementation, it would be a new subcategory (intron mutagenesis) and look just like transposon mutagenesis in terms of data fields.

**Comment by djow2019** [comment]
@khybiske Can you find an appropriate ontology term for intron mutagenesis? (Also need one for transposon mutagenesis)

As an example, we use EFO:0000370 for chemical mutagenesis 
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000370

**Comment by djow2019** [comment]
Potential candidate for transposon mutagenesis: EFO_0004021

**Comment by khybiske** [comment]
@djow2019 Noticing a bug. After I authorize myself on chlambase, your new mutant annotation sections (introns, recombination) disappear. They are visible pre-authorization.

**Comment by djow2019** [comment]
Ugh its an oauth issue. You get redirected back to the original chlambase site.... Will need to think about this

**Comment by djow2019** [comment]
@andrewsu Users won't be able to make annotations to wikidata from chlambase dev because the callback URL is different. Won't be able to fix this without making a new Chlambase Dev instance on media wiki (and then wait for approval...).
For mutants, I could also disable the authorization check, but then I'm not sure if that is a good idea because information in chlambase dev won't be copied to production. Thoughts?

**Comment by djow2019** [comment]
Discussed with Andrew about this. We won't make a separate oauth application for chlambase dev, so making annotations on the dev site won't be possible.

**Comment by khybiske** [comment]
@djow2019 Totally ok with that. Possible to push new mutant annotation categories to main site in the near future? Seems like that would be a stable one, and then I can go about adding annotations.
